BEGIN TRANSACTION;
CREATE TABLE USERS (
  APS_ID INT PRIMARY KEY,
  EMAIL TEXT,
  OAUTH TEXT
);
CREATE TABLE BIKES (
  BIKE_ID INT PRIMARY KEY,
  AVAILIBLE BOOLEAN,
  APS_ID INT,
  LAST INT REFERENCES TRANSACTIONS(TRANS_ID)
);
CREATE TABLE TRANSACTIONS (
  TRANS_ID INT PRIMARY KEY,
  APS_ID INT REFERENCES  USERS(APS_ID) ,
  BIKE_ID INT REFERENCES BIKES(BIKE_ID) ,
  WITHDRAW BOOLEAN,
  TRANS_TIME TIME
);
COMMIT;
